[phases.setup]
commands = ["cd front-vue"]

[phases.install]
commands = ["npm install"]

[phases.build]
commands = ["npm run build"]

[phases.start]
commands = ["npm run serve"] # Cambia según el script que uses para producción